export const product = [
    {
        id: 1,
        img: "/assets/images/yummy-master.png",
        title: "Yummy and Tasty Food Conner",
        zip: "/assets/zip/yummy-master.zip",
        link: "https://phenomenal-sable-00909e.netlify.app/",
        heading:"Savor Delicious Dishes at Yummy and Tasty Food Corner",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Discover a delightful range of mouthwatering dishes at Yummy and Tasty Food Conner.",
        para: "From appetizers to desserts, our menu is crafted to satisfy every craving. Enjoy the cozy ambiance and exceptional service that make dining with us a memorable experience."
    },
    {
        id: 2,
        img: "/assets/images/yoga.PNG",
        title: "Yoga",
        zip: "/assets/zip/yoga.zip",
        link: "https://illustrious-sunburst-34d7c1.netlify.app/",
        heading:"Find Your Inner Peace with Our Yoga Classes",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Achieve tranquility and wellness through our comprehensive yoga program.",
        para: "Whether you're a beginner or an advanced practitioner, our classes cater to all levels. Join us to enhance your flexibility, strength, and mental clarity in a supportive environment."
    },
    {
        id: 3,
        img: "/assets/images/woody.PNG",
        title: "Woody",
        zip: "/assets/zip/woody.zip",
        link: "https://stalwart-kataifi-ec86b3.netlify.app/",
        heading:"Adventure Awaits: Experience Nature with Woody",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Experience nature like never before with Woody, your ultimate outdoor adventure guide.",
        para: "Explore breathtaking landscapes, engage in exciting activities, and reconnect with nature. Woody provides everything you need for a thrilling and rejuvenating outdoor experience."
    },
    {
        id: 4,
        img: "/assets/images/wilcon.PNG",
        title: "Wilcon",
        zip: "/assets/zip/wilcon.zip",
        link: "https://amazing-froyo-72d8b8.netlify.app/",
        heading:"Transform Your Home with Wilcon's Quality Products",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Wilcon offers top-quality home improvement products for all your renovation needs.",
        para: "From tools to materials, we provide everything you need to create your dream home. Our expert advice and exceptional customer service make your projects a breeze."
    },
    {
        id: 5,
        img: "/assets/images/vira.PNG",
        title: "Vira",
        zip: "/assets/zip/vira.zip",
        link: "https://animated-crepe-592e41.netlify.app/",
        heading:"Elevate Your Style with Vira's Fashion Collection",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Vira is your go-to solution for stylish and functional fashion.",
        para: "Explore our collection of trendy apparel that combines comfort and style, perfect for any occasion. Elevate your wardrobe with Vira's unique designs and quality fabrics."
    },
    {
        id: 6,
        img: "/assets/images/Villa.PNG",
        title: "Villa",
        zip: "/assets/zip/Villa.zip",
        link: "https://mellifluous-strudel-94bdea.netlify.app/",
        heading:"Design Your Dream Home with Villa's Expertise",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Discover luxurious living with Villa, your ideal home design partner.",
        para: "We specialize in creating stunning interiors that reflect your personal style. From modern to traditional, Villa transforms spaces into dream homes tailored to your taste."
    },
    {
        id: 7,
        img: "/assets/images/travela.PNG",
        title: "Travela",
        zip: "/assets/zip/travela.zip",
        link: "https://animated-gaufre-fd82a9.netlify.app/",
        heading:"Explore the World: Your Travel Journey Begins Here",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Explore the world with Travela, your trusted travel companion.",
        para: "From exciting destinations to unique experiences, Travela helps you plan unforgettable trips tailored to your interests. Discover new adventures and create lasting memories."
    },
    {
        id: 8,
        img: "/assets/images/tour.PNG",
        title: "Tour",
        zip: "/assets/zip/tour.zip",
        link: "https://delightful-dasik-9249b9.netlify.app/",
        heading:"Discover New Cultures with Our Guided Tours",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Join our immersive tours and experience the world like never before.",
        para: "Whether you prefer cultural exploration or nature hikes, our expert guides provide insights and experiences that enrich your journey. Book your next adventure today!"
    },
    {
        id: 9,
        img: "/assets/images/timer-master.PNG",
        title: "Timer",
        zip: "/assets/zip/timer-master.zip",
        link: "https://quiet-shortbread-fe5593.netlify.app/",
        heading:"Master Time Management with Our Timer Tool",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Stay on schedule with Timer, your ultimate time management tool.",
        para: "Designed for efficiency, Timer helps you prioritize tasks, set reminders, and boost productivity. Take control of your time and achieve your goals with ease."
    },
    {
        id: 10,
        img: "/assets/images/TeaHouse.PNG",
        title: "Tea House",
        zip: "/assets/zip/TeaHouse.zip",
        link: "https://splendorous-salamander-d44b89.netlify.app/",
        heading:"Relax and Enjoy Premium Teas at Tea House",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Immerse yourself in the tranquil atmosphere of Tea House, a haven for tea lovers.",
        para: "With a diverse selection of premium teas from around the world, our expert staff guides you through an exquisite tasting experience that delights the senses."
    },
    {
        id: 11,
        img: "/assets/images/tasty-master.PNG",
        title: "Tasty Restaurant",
        zip: "/assets/zip/tasty-master.zip",
        link: "https://timely-boba-d72850.netlify.app/",
        heading:"Indulge in Culinary Delights at Tasty Restaurant",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Indulge in a culinary adventure at Tasty Restaurant, where every dish tells a story.",
        para: "Our talented chefs use fresh ingredients to create innovative dishes that celebrate global flavors. Join us for an unforgettable dining experience."
    },
    {
        id: 12,
        img: "/assets/images/sports-master.PNG",
        title: "Sports",
        zip: "/assets/zip/sports-master.zip",
        link: "https://remarkable-cascaron-25dcdd.netlify.app/",
        heading:"Elevate Your Game with Our Sports Programs",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Get ready to elevate your game with our comprehensive sports programs.",
        para: "From training sessions to competitive leagues, we offer a variety of options for athletes of all levels. Join our community and unleash your full potential!"
    },
    {
        id: 13,
        img: "/assets/images/portFoilo.PNG",
        title: "Port Foilo",
        zip: "/assets/zip/shop.zip",
        link: "https://singular-sfogliatella-5b079e.netlify.app/",
        heading:"Shop the Latest Trends at Port Foilo",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Shop the latest fashion trends at our premier clothing store.",
        para: "We offer a wide range of styles to suit every taste and occasion. Discover unique pieces that express your individuality and keep your wardrobe fresh."
    },
    {
        id: 14,
        img: "/assets/images/shoes-shop.PNG",
        title: "Shoes",
        zip: "/assets/zip/shoes-shop.zip",
        link: "https://taupe-heliotrope-fbe70b.netlify.app/",
        heading:"Step Into Style with Our Shoe Collection",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Step into style with our extensive collection of footwear.",
        para: "From casual to formal, our shoe selection combines comfort and fashion, ensuring you find the perfect pair for any occasion."
    },
    {
        id: 15,
        img: "/assets/images/Scholor.PNG",
        title: "School",
        zip: "/assets/zip/scholar.zip",
        link: "https://glittery-chimera-e85adc.netlify.app/",
        heading:"Inspire Learning and Growth at Scholar Academy",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Welcome to Scholar, where education meets innovation.",
        para: "We offer a range of programs designed to inspire and equip students for success. Join our community and unlock your potential with our dedicated faculty."
    },
    {
        id: 16,
        img: "/assets/images/restaurant.PNG",
        title: "Family Restaurant",
        zip: "/assets/zip/restaurant.zip",
        link: "https://loquacious-cheesecake-aa10ae.netlify.app/",
        heading:"Create Lasting Memories at Our Family Restaurant",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Gather with loved ones at our warm and inviting Family Restaurant.",
        para: "With a menu that caters to all ages, we create a friendly atmosphere perfect for family celebrations or casual dinners. Join us for a meal filled with love and laughter."
    },
    {
        id: 17,
        img: "/assets/images/real-estate.PNG",
        title: "Real Estate",
        zip: "/assets/zip/real-estate.zip",
        link: "https://funny-mandazi-8d8164.netlify.app/",
        heading:"Find Your Dream Home with Our Real Estate Services",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Find your dream property with our expert real estate services.",
        para: "We provide personalized guidance throughout the buying or selling process, ensuring you make informed decisions in the dynamic real estate market."
    },
    {
        id: 18,
        img: "/assets/images/hexashop.PNG",
        title: "Hexa Shop",
        zip: "/assets/zip/hexashop.zip",
        link: "https://stunning-blancmange-6bf49c.netlify.app/",
        heading:"Unleash Adventure with Thrilling Experiences at Hexa Shop",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Experience the adrenaline rush with Rage, the ultimate action-packed adventure.",
        para: "From thrilling rides to intense competitions, Rage offers an electrifying experience for thrill-seekers. Join us and unleash your inner adventurer!"
    },
    {
        id: 19,
        img: "/assets/images/pets.PNG",
        title: "Pets",
        zip: "/assets/zip/pets.zip",
        link: "https://glittery-gecko-c1576e.netlify.app/",
        heading:"Celebrate Your Furry Friends with Our Pet Services",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Celebrate the joy of pet ownership with our dedicated services.",
        para: "From grooming to training, we provide everything you need to ensure your furry friends are happy and healthy. Join our community of pet lovers today!"
    },
    {
        id: 20,
        img: "/assets/images/property.PNG",
        title: "Property",
        zip: "/assets/zip/property.zip",
        link: "https://magnificent-malabi-e6ad69.netlify.app/",
        heading:"Discover Your Ideal Property with Our Expert Help",
        head:"Enjoy all the benefits of an our subscription.",
        discription: "Explore premium properties with our comprehensive real estate listings.",
        para: "Whether you're looking to buy, sell, or rent, our expert team is here to assist you in finding the perfect property that meets your needs."
    },
];
